### PR TITLE
Add ping in special.py (TEST)

### PR DESCRIPTION
**Pull request by shanutheflash**

### CODE REVIEW

**Comment by shanutheflash** [comment]
Oof

**Comment by Tissotsaksham** [comment]
@shanutheflash Bhaggg jaa bsdk

**Comment by lzzy12** [comment]
@Tissotsaksham Wtf

**Comment by lzzy12** [comment]
@lzzy12 Lmao

**Comment by lzzy12** [comment]
@lzzy12

**Comment by shanutheflash** [comment]
@Tissotsaksham Just die bc

**Pull request closed without merging**
